### ISSUE TITLE
AttributeError: flag_values_dict

### ISSUE THREAD

**Issue by indukantdeo** [loliverhennigh/Steady-State-Flow-With-Neural-Nets#1]
@loliverhennigh 
while running the script for flow_test following error pops up:
Traceback (most recent call last):
  File "flow_train.py", line 27, in <module>
    TRAIN_DIR = make_checkpoint_path(FLAGS.base_dir, FLAGS)
  File "../utils/experiment_manager.py", line 12, in make_checkpoint_path
    for k in FLAGS.flag_values_dict().keys():
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 58, in __getattr__
    raise AttributeError(name)
AttributeError: flag_values_dict

**Comment by loliverhennigh** [comment]
This was caused by an update to Tensorflow but I changed it should be working now.

**Comment by joshuamills98** [comment]
@loliverhennigh I believe they removed tf.app in TensorFlow 2
